version: '3'
services:
  janusgraph:
    build: "./"
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb:8000
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
      - HTTPS_CRT=${JANUSGRAPH_CRT}
      - HTTPS_KEY=${JANUSGRAPH_KEY}
      - LISTEN_PORT=8182
    healthcheck:
      test: ["CMD-SHELL", "curl -kf https://localhost:8182/?gremlin=1; if [ $$? -eq 22 ]; then exit 0; else exit 1; fi"]
      interval: 1s
      timeout: 20s
      retries: 20
    depends_on:
      - "dynamodb"
      - "elasticsearch"
  dynamodb:
    build:
      context: "."
      dockerfile: "dynamodb.Dockerfile"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/shell/ || exit 1"]
      interval: 1s
      timeout: 10s
      retries: 3
  elasticsearch:
    image: "elasticsearch:5.6-alpine"
    environment:
      - "discovery.type=single-node"
    healthcheck:
      test: ["CMD-SHELL", "curl -sSf http://localhost:9200/"]
      interval: 1s
      timeout: 10s
      retries: 3
